import io
from datetime import datetime

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

_styles = getSampleStyleSheet()
_styles.add(ParagraphStyle(name="ReportTitle", parent=_styles["Title"], fontSize=20))
_styles.add(ParagraphStyle(name="ReportBody", parent=_styles["Normal"], leading=15, spaceAfter=8))
_styles.add(ParagraphStyle(name="ReportSmall", parent=_styles["Normal"], fontSize=8.5, textColor=colors.grey))


def generate_transparency_report_pdf(org, report_row, donor_total, donation_count, usage_summary):
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=letter,
        topMargin=0.7 * inch, bottomMargin=0.7 * inch,
        leftMargin=0.75 * inch, rightMargin=0.75 * inch,
    )
    story = []

    story.append(Paragraph("Donor Transparency Report", _styles["ReportTitle"]))
    story.append(Spacer(1, 4))
    story.append(Paragraph(f"Organization: {org['org_name']}", _styles["ReportBody"]))
    story.append(Paragraph(f"Registration No.: {org.get('registration_number') or 'Not provided'}", _styles["ReportBody"]))
    story.append(Paragraph(f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M')}", _styles["ReportSmall"]))
    story.append(Spacer(1, 14))

    story.append(Paragraph("Your Contribution Summary", _styles["Heading2"]))
    summary_data = [
        ["Total Donated", f"Rs. {donor_total:,.0f}"],
        ["Number of Donations", str(donation_count)],
    ]
    t = Table(summary_data, colWidths=[3 * inch, 3 * inch])
    t.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f0f0f0")),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
    ]))
    story.append(t)
    story.append(Spacer(1, 16))

    story.append(Paragraph("Transparency Score", _styles["Heading2"]))
    if report_row and report_row.get("transparency_score") is not None:
        story.append(Paragraph(f"{report_row['transparency_score']} / 100", _styles["ReportBody"]))
        if report_row.get("red_flags"):
            story.append(Paragraph("Red Flags Identified:", _styles["ReportBody"]))
            for flag in report_row["red_flags"].split(", "):
                story.append(Paragraph(f"- {flag}", _styles["ReportBody"]))
        else:
            story.append(Paragraph("No red flags detected in the most recent report.", _styles["ReportBody"]))
        story.append(Paragraph(
            f"Based on report uploaded: {report_row.get('uploaded_at', 'N/A')}", _styles["ReportSmall"]
        ))
    else:
        story.append(Paragraph("No financial report has been analyzed for this organization yet.", _styles["ReportBody"]))
    story.append(Spacer(1, 16))

    story.append(Paragraph("How Your Money Was Used", _styles["Heading2"]))
    story.append(Paragraph(usage_summary or "No AI usage summary available yet.", _styles["ReportBody"]))
    story.append(Spacer(1, 20))

    story.append(Paragraph(
        "This report is generated by the Donation Transparency Checker platform based on the "
        "organization's self-submitted financial report. It is an interpretive summary, not an "
        "independently verified audit.",
        _styles["ReportSmall"]
    ))

    doc.build(story)
    buf.seek(0)
    return buf.getvalue()


def generate_certificate_pdf(donor_name, org_name, total_amount):
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=letter, topMargin=1.2 * inch)
    story = []

    story.append(Paragraph("Certificate of Donation", _styles["ReportTitle"]))
    story.append(Spacer(1, 30))
    story.append(Paragraph(f"This certifies that <b>{donor_name}</b>", _styles["ReportBody"]))
    story.append(Paragraph(
        f"has generously donated a total of <b>Rs. {total_amount:,.0f}</b> to <b>{org_name}</b>.",
        _styles["ReportBody"]
    ))
    story.append(Spacer(1, 20))
    story.append(Paragraph(f"Issued on: {datetime.now().strftime('%Y-%m-%d')}", _styles["ReportSmall"]))
    story.append(Paragraph(
        "This certificate is issued via the Donation Transparency Checker platform.",
        _styles["ReportSmall"]
    ))

    doc.build(story)
    buf.seek(0)
    return buf.getvalue()